project_id = "gtjxdvmwiglnnquyruzf"

[functions.manage-clients]
verify_jwt = false

[functions.parse-m3u]
verify_jwt = false

[functions.channel-monitor]
verify_jwt = false

[functions.channel-votes]
verify_jwt = false